import { Link, useParams } from 'react-router-dom';

const featureCopy: Record<string,{eyebrow:string,title:string,description:string,bullets:string[],status:'operacional'|'futuro'}> = {
  agenda:{eyebrow:'Agenda odontológica',title:'A disponibilidade real da clínica, não só quadradinhos no calendário.',description:'O Worker valida tenant, membership, paciente, profissional, recurso, bloqueios e conflitos; transações com locks protegem concorrência.',bullets:['Controle por profissional e cadeira/sala','Conflito validado fora do frontend','Bloqueios da clínica','Cancelamento libera o horário'],status:'operacional'},
  prontuario:{eyebrow:'Prontuário clínico',title:'Histórico clínico com rastreabilidade.',description:'Registros originais são append-only e correções importantes entram como novos adendos com motivo, autoria e auditoria.',bullets:['Notas clínicas','Original imutável','Autoria e timestamp','Adendos rastreáveis'],status:'operacional'},
  odontograma:{eyebrow:'Odontograma',title:'Em fase futura do produto.',description:'A estrutura de domínio está mapeada, mas o fluxo operacional do odontograma ainda não está disponível.',bullets:['Ainda não disponível','Sem estado clínico derivado em runtime','Fora do Core P0'],status:'futuro'},
  'fotos-clinicas':{eyebrow:'Fotos clínicas',title:'Mídia clínica com acesso privado.',description:'Upload e leitura passam pelo Worker, que valida usuário, tenant, membership, permission e vínculo com o paciente.',bullets:['JPEG, PNG e WebP validados','Limite técnico de 15 MiB','R2 privado e chave scoped','Download autenticado; sem URL pública'],status:'operacional'},
  tratamentos:{eyebrow:'Planos de tratamento',title:'Em fase futura do produto.',description:'Planejamento e aceite de tratamento não fazem parte do núcleo clínico operacional deste estágio.',bullets:['Ainda não disponível','Sem aceite ou execução em runtime','Fora do Core P0'],status:'futuro'}
};

export function FeaturePage(){
  const {feature='agenda'}=useParams();
  const item=featureCopy[feature] ?? featureCopy.agenda;
  return <main className="feature-page-public"><header className="marketing-nav marketing-container"><Link className="brand" to="/"><span className="brand-mark">O</span><span>OdontoFlow</span></Link><Link className="btn secondary" to="/">← Voltar</Link></header><section className="feature-hero marketing-container"><span className="eyebrow">{item.eyebrow} · {item.status === 'operacional' ? 'núcleo atual' : 'fase futura'}</span><h1>{item.title}</h1><p>{item.description}</p><div className="hero-actions">{item.status === 'operacional' && <Link className="btn primary large" to="/demo-clinica/app">Ver demonstração</Link>}<Link className="btn secondary large" to="/precos">Ver planos</Link></div></section><section className="marketing-container feature-detail-grid">{item.bullets.map((b,i)=><article className="feature-card" key={b}><span className="feature-icon">0{i+1}</span><h3>{b}</h3><p>{item.status === 'operacional' ? 'Disponível no núcleo funcional desta vertical.' : 'Fora do Core P0; não está disponível no runtime atual.'}</p></article>)}</section></main>;
}
