import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';

const slots=['09:00','10:30','14:00','15:30','17:00'];
export function PublicBookingPage(){
  const {tenantSlug='demo-clinica'}=useParams();
  const [step,setStep]=useState(1);
  const [selected,setSelected]=useState('14:00');
  return <main className="booking-page"><section className="booking-card"><div className="booking-top"><Link to={`/${tenantSlug}`} className="brand"><span className="brand-mark">A</span><span>Clínica Aurora</span></Link><span aria-live="polite">Etapa {step} de 3</span></div>{step===1&&<><span className="eyebrow">Agendamento online</span><h1>O que você precisa?</h1><div className="booking-options"><button type="button" onClick={()=>setStep(2)}><b>Consulta e avaliação</b><span>60 min • valor confirmado pela clínica</span></button><button type="button" onClick={()=>setStep(2)}><b>Profilaxia</b><span>60 min • acompanhamento preventivo</span></button><button type="button" onClick={()=>setStep(2)}><b>Restauração</b><span>Duração depende da avaliação</span></button></div></>}{step===2&&<><span className="eyebrow">Escolha um horário</span><h1>Quinta-feira, 5 de outubro</h1><p className="muted">Os slots são demonstrativos. Em produção serão derivados da agenda, profissional, duração, bloqueios e recurso físico.</p><div className="slot-grid">{slots.map(s=><button type="button" className={selected===s?'selected':''} aria-pressed={selected===s} onClick={()=>setSelected(s)} key={s}>{s}</button>)}</div><div className="booking-actions"><button type="button" className="btn secondary" onClick={()=>setStep(1)}>← Voltar</button><button type="button" className="btn primary" onClick={()=>setStep(3)}>Continuar →</button></div></>}{step===3&&<><span className="eyebrow">Revisão</span><h1>Quase lá.</h1><div className="booking-summary"><div><span>Serviço</span><b>Consulta e avaliação</b></div><div><span>Horário</span><b>05/10 • {selected}</b></div><div><span>Clínica</span><b>Clínica Aurora</b></div></div><p className="muted">A confirmação real deve ocorrer em uma transação segura no backend. Esta fundação não grava agendamentos públicos ainda.</p><div className="booking-actions"><button type="button" className="btn secondary" onClick={()=>setStep(2)}>← Voltar</button><Link className="btn primary" to={`/${tenantSlug}/cadastro`}>Continuar para cadastro →</Link></div></>}</section></main>
}
